### ISSUE TITLE
Problem compiling Grub

### ISSUE THREAD

**Issue by pguarache** [coherixmatts/grub-2.04#2]
Hi! I'm having the follonwing error trying to compliling Grub

automake: error: cannot open < Makefile.util.am: No such file or directory
autoreconf: error: automake failed with exit status: 1
./bootstrap: autoreconf failed

And yes. The file is not there. How can I fix the problem?

Also, I want to know If I can use this code to to build a x64 version to be used in a Surface Go. I really want to control Grub with the Volume buttons.

**Comment by mattschwantes** [comment]
This version doesn't have volume button based controls. That was added by someone in one of the forks.

**Comment by mattschwantes** [comment]
What are you using to compile? Device, architecture, distro, etc?

**Comment by pguarache** [comment]
Yes! I know that fork. But it doesn't have that file either. I'm using Ubuntu 22.04 x64 on a Surface Go to compile the file.

**Comment by mattschwantes** [comment]
It appears to be an issue with Python versions.  These instructions are quite old and were previously tested using Ubuntu 14.04 (which I believe was using Python2).  I tried just now using an Ubuntu 20.04.05 LTS LiveCD and encountered the issue you observed. 

I was able to work around this by changing Line 11 of autogen.sh to : ${PYTHON:=python3}

**Comment by pguarache** [comment]
Thanks! I'm goin to try it right away.

**Comment by mattschwantes** [comment]
It has some further issues in the configure step afterward unfortunately

**Comment by pguarache** [comment]
If not. I guess is better to use Ubutun 14.04 to compile the file.

**Comment by mattschwantes** [comment]
If you are building this to boot an ARM32 device like Surface RT1 or Surface RT2 (which is the intended purpose), please also 
install autoconf, automount, bison, flex and  gcc-arm-linux-gnueabihf prior to Step 2. Then everything works as instructed.

**Comment by mattschwantes** [comment]
If you're building this to boot an x86-64 system like Surface Go, these instructions won't work for that as-is because they are intended for 32-bit ARM devices.

**Comment by pguarache** [comment]
Haven't get to that step yet. But... i'm going to try it anyways.

**Comment by pguarache** [comment]
I'm going to change -O arm-efi to -O x86_64-efi

**Comment by mattschwantes** [comment]
OK. Let me know how it goes. Good luck

**Comment by pguarache** [comment]
Hi! After uninstalling grub2, and do all the procedure again, adding the make install part, manual deleting the /boot/grub folder, then sudo grub-install /dev/dev/nvme0n1... I was able to boot into the **grub-2.04-nokeymod**. The countdown works fine, but the buttons don't work... Let me do all again from the beggining but cleanning all first.
